# =============================================================================
# Script:  qsf_extract.R
#
# Purpose: Extract the QID-to-label mapping from any Qualtrics .qsf file and
#          write it to qid_map.R, ready to be sourced by clean_tracker.R.
#          Labels are the Qualtrics export tags (e.g. "Q16", "prolific_id").
#
# Usage:
#   1. Runs as part of clean_tracker.R, which sources this script to generate qid_map.R.
#
# Input:   Any Qualtrics .qsf file (via Tools -> Export Survey)
# Output:  code/qid_map.R  +  output/qualtrics_variable_list.txt
# =============================================================================

library(jsonlite)
library(stringr)

# Uncomment the following lines if running this script standalone. 
# Ignore if sourcing from clean_tracker.R

# Path to your .qsf file 
#qsf_path <- "qualtrics survey file/Test_Import_From_QSF.qsf"

# Output path for the generated qid_map
#qid_map_path <- "code/qid_map.R"

# Output path for the human-readable variable list
#qid_table_path <- "data/qualtrics_variable_list.txt"

# Question types to exclude — not real survey pages, will not appear in
# tracking_json (Timing = page timers, Meta = browser metadata)
exclude_types <- c("Timing", "Meta")


# =============================================================================
# Parse QSF and extract question metadata
# =============================================================================

qsf      <- fromJSON(qsf_path, simplifyVector = FALSE)
elements <- qsf$SurveyElements
questions <- Filter(function(el) el$Element == "SQ", elements)

extract_question <- function(el) {
  qid     <- el$PrimaryAttribute
  payload <- el$Payload
  tag   <- if (!is.null(payload$DataExportTag)) payload$DataExportTag else NA
  qtype <- if (!is.null(payload$QuestionType))  payload$QuestionType  else NA
  qtext <- if (!is.null(payload$QuestionText))  payload$QuestionText  else NA

  # Strip HTML tags and collapse whitespace for display
  qtext_clean <- str_squish(str_remove_all(qtext, "<[^>]+>"))
  qtext_short <- if (!is.na(qtext_clean) && nchar(qtext_clean) > 70)
    paste0(substr(qtext_clean, 1, 70), "...") else qtext_clean

  data.frame(QID = qid, ExportTag = tag, Type = qtype,
             Question = qtext_short, stringsAsFactors = FALSE)
}

result <- do.call(rbind, lapply(questions, extract_question))
result <- result[order(result$QID), ]


# =============================================================================
# Print summary table  +  write to file
# =============================================================================

sep  <- paste(rep("=", 80), collapse = "")
sep2 <- paste(rep("-", 80), collapse = "")

table_lines <- c(
  "",
  sep,
  "QID MAPPING TABLE",
  sprintf("Generated: %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
  sprintf("Source:    %s", qsf_path),
  sep,
  sprintf("%-10s  %-20s  %-12s  %s", "QID", "ExportTag", "Type", "Question"),
  sep2
)

for (i in seq_len(nrow(result))) {
  table_lines <- c(table_lines, sprintf(
    "%-10s  %-20s  %-12s  %s",
    result$QID[i],
    ifelse(is.na(result$ExportTag[i]), "-", result$ExportTag[i]),
    ifelse(is.na(result$Type[i]),      "-", result$Type[i]),
    ifelse(is.na(result$Question[i]),  "-", result$Question[i])
  ))
}

table_lines <- c(table_lines, sep)

cat(paste(table_lines, collapse = "\n"), "\n")

if (exists("qid_table_path") && !is.null(qid_table_path)) {
  writeLines(table_lines, qid_table_path)
  cat(sprintf("Variable list written to: %s\n", qid_table_path))
}


# =============================================================================
# Write qid_map.R  (excluding Timing, Meta questions)
# =============================================================================

map_rows <- result[!result$Type %in% exclude_types, ]

lines <- c(
  "# Auto-generated by qsf_extract.R — review before use.",
  "# Labels are Qualtrics export tags. Remove unneeded entries.",
  "# Source from clean_tracker.R: source(\"code/qid_map.R\")",
  "",
  "qid_map <- c("
)

for (i in seq_len(nrow(map_rows))) {
  comma <- if (i < nrow(map_rows)) "," else ""
  lines <- c(lines, sprintf('  %-8s = "%s"%s   # %s',
                            map_rows$QID[i],
                            map_rows$ExportTag[i],
                            comma,
                            map_rows$Question[i]))
}

lines <- c(lines, ")")

writeLines(lines, qid_map_path)

cat(sprintf(
  "\nWritten to: %s  (%d entries)\n\n", qid_map_path, nrow(map_rows)
))
